// Match patterns for the Group B checks.
//
// These live in ONE place because they are used in two runtimes: the analyzer in
// scanGroupB.ts, and the browser code that runs inside Browserless (which cannot
// import modules, so processScan passes this object in as session context).
// All patterns are lowercase substrings — deliberately simpler than regex, so a
// pattern can never behave differently on the two sides.

export const PATTERNS = {
  // Anchor text/href → privacy policy page
  privacy: [
    'privacy policy', 'privacy notice', 'privacy statement',
    '/privacy', '/privacy-policy', '/legal/privacy',
  ],
  // Anchor text/href → accessibility statement page
  a11y: ['accessibility statement', 'accessibility policy', '/accessibility'],
  // Anchor text/href → opt-out of sale/sharing
  doNotSell: [
    'do not sell', 'do not share', 'your privacy choices',
    'limit the use of my sensitive personal information',
    '/do-not-sell', '/donotsell', '/privacy-choices',
  ],
  // Language that indicates a consent moment
  consentText: [
    'we use cookies', 'this site uses cookies', 'this website uses cookies',
    'uses cookies', 'cookie preferences', 'cookie settings',
    'your privacy choices', 'cookies',
  ],
  // Controls inside a consent banner
  consentControl: [
    'accept', 'agree', 'allow all', 'allow cookies', 'got it',
    'reject', 'decline', 'refuse', 'only necessary', 'essential only',
  ],
  // A rights-request mechanism
  request: [
    'delete my data', 'delete my information', 'access my data', 'access my information',
    'data request', 'data subject request', 'subject access request',
    'exercise your rights', 'exercise my rights', 'submit a request',
    'privacy request', 'request my data', 'data rights request',
  ],
  // An accessibility feedback channel
  a11yReport: [
    'report a barrier', 'report an accessibility', 'report accessibility',
    'accessibility issue', 'accessibility issues', 'accessibility feedback',
    'accessibility barrier', 'accessibility concern',
  ],
  // AI language stated AS A DISCLOSURE — the only thing that earns FOUND.
  aiDisclosureStrong: [
    'interacting with an automated', 'interacting with ai', 'interacting with an ai',
    'you are not speaking with a human', 'not a human', 'rather than a person',
    'powered by artificial intelligence', 'powered by ai', 'ai disclosure',
    'use of artificial intelligence', 'ai-generated response', 'ai generated response',
    'automated system rather than', 'may be interacting with',
    'we use artificial intelligence', 'responses are generated by',
  ],
  // AI mentioned at all — earns COULD NOT DETERMINE, never NOT FOUND.
  aiAny: [
    'artificial intelligence', 'ai-powered', 'ai powered', 'automated system',
    'chatbot', 'chat bot', 'ai assistant', 'generative ai', 'large language model',
  ],
};

// Known consent-management vendors, matched against script sources, inline
// script text, page text, and network requests.
export const CMP_MATCHERS = [
  { match: 'onetrust', vendor: 'OneTrust' },
  { match: 'cookielaw.org', vendor: 'OneTrust' },
  { match: 'cookiebot', vendor: 'Cookiebot' },
  { match: 'cookieyes', vendor: 'CookieYes' },
  { match: 'termly', vendor: 'Termly' },
  { match: 'complianz', vendor: 'Complianz' },
  { match: 'osano', vendor: 'Osano' },
  { match: 'iubenda', vendor: 'iubenda' },
  { match: 'enzuzo', vendor: 'Enzuzo' },
  { match: 'quantcast', vendor: 'Quantcast Choice' },
  { match: 'didomi', vendor: 'Didomi' },
  { match: 'usercentrics', vendor: 'Usercentrics' },
  { match: 'datarightsos', vendor: 'DataRightsOS' },
  { match: 'dros-root', vendor: 'DataRightsOS' },
  { match: 'termsfeed', vendor: 'TermsFeed' },
  { match: 'civicuk.com/cookie', vendor: 'Civic Cookie Control' },
];